// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcM_fN_hmE_rFfViF8R1EIE1BTCDushs',
    appId: '1:83891236587:web:e8824e9fabf5fce97f18ae',
    messagingSenderId: '83891236587',
    projectId: 'triviagame-5bb67',
    authDomain: 'triviagame-5bb67.firebaseapp.com',
    databaseURL: 'https://triviagame-5bb67-default-rtdb.firebaseio.com',
    storageBucket: 'triviagame-5bb67.firebasestorage.app',
    measurementId: 'G-WZN4CKPZVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCnAfHag4XVzzWLishiaYTFi1IPAPhhbqA",
    appId: "1:83891236587:android:b6222eb6269afd7a7f18ae",
    messagingSenderId: '83891236587',
    projectId: 'triviagame-5bb67',
    databaseURL: 'https://triviagame-5bb67-default-rtdb.firebaseio.com',
    storageBucket: 'triviagame-5bb67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6BXY-SXgD5gh58Ggg95Gk-XS-cnat6NE',
    appId: '1:83891236587:ios:d7b55bd97a5e29077f18ae',
    messagingSenderId: '83891236587',
    projectId: 'triviagame-5bb67',
    databaseURL: 'https://triviagame-5bb67-default-rtdb.firebaseio.com',
    storageBucket: 'triviagame-5bb67.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6BXY-SXgD5gh58Ggg95Gk-XS-cnat6NE',
    appId: '1:83891236587:ios:d7b55bd97a5e29077f18ae',
    messagingSenderId: '83891236587',
    projectId: 'triviagame-5bb67',
    databaseURL: 'https://triviagame-5bb67-default-rtdb.firebaseio.com',
    storageBucket: 'triviagame-5bb67.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWcM_fN_hmE_rFfViF8R1EIE1BTCDushs',
    appId: '1:83891236587:web:e8824e9fabf5fce97f18ae',
    messagingSenderId: '83891236587',
    projectId: 'triviagame-5bb67',
    authDomain: 'triviagame-5bb67.firebaseapp.com',
    databaseURL: 'https://triviagame-5bb67-default-rtdb.firebaseio.com',
    storageBucket: 'triviagame-5bb67.firebasestorage.app',
    measurementId: 'G-WZN4CKPZVT',
  );

}